// Script to create sample events for testing
import prisma from '../server/db';

async function createSampleEvents() {
  console.log('Creating sample events...');

  const events = [
    {
      event_code: 'EVT-2025-001',
      event_name: 'សន្និសីទជាតិស្តីពីការអប់រំឌីជីថល',
      event_name_english: 'National Digital Education Conference',
      event_description: 'សន្និសីទជាតិស្តីពីការអប់រំឌីជីថល នឹងពិភាក្សាអំពីការប្រើប្រាស់បច្ចេកវិទ្យាក្នុងការបង្រៀន និងការរៀន។ វាគ្មិនពិសេសពីក្រសួងអប់រំ និងអ្នកជំនាញអន្តរជាតិ។',
      event_type: 'CONFERENCE',
      event_category: 'TECHNOLOGY',
      event_format: 'HYBRID',
      event_status: 'UPCOMING',
      event_start_date: new Date('2025-02-15'),
      event_end_date: new Date('2025-02-17'),
      registration_deadline: new Date('2025-02-10'),
      event_location: 'រាជធានីភ្នំពេញ',
      event_venue: 'សណ្ឋាគារ Sokha',
      province_name: 'រាជធានីភ្នំពេញ',
      district_name: 'ខណ្ឌចំការមន',
      virtual_platform: 'Zoom',
      virtual_meeting_url: 'https://zoom.us/j/example',
      max_attendees: 500,
      current_attendees: 127,
      allow_public_registration: true,
      requires_approval: true,
      is_multi_track: true,
      is_published: true,
      tags: ['ឌីជីថល', 'បច្ចេកវិទ្យា', 'ការអប់រំ'],
    },
    {
      event_code: 'EVT-2025-002',
      event_name: 'សិក្ខាសាលាអភិវឌ្ឍជំនាញគ្រូបង្រៀន',
      event_name_english: 'Teacher Professional Development Workshop',
      event_description: 'សិក្ខាសាលាពីរថ្ងៃសម្រាប់គ្រូបង្រៀនវិទ្យាល័យ។ រៀនបច្ចេកទេសបង្រៀនទំនើប និង ការគ្រប់គ្រងថ្នាក់រៀន។',
      event_type: 'WORKSHOP',
      event_category: 'PROFESSIONAL_DEVELOPMENT',
      event_format: 'IN_PERSON',
      event_status: 'UPCOMING',
      event_start_date: new Date('2025-03-05'),
      event_end_date: new Date('2025-03-06'),
      registration_deadline: new Date('2025-02-28'),
      event_location: 'ខេត្តសៀមរាប',
      event_venue: 'មជ្ឈមណ្ឌលបណ្តុះបណ្តាលគ្រូ',
      province_name: 'ខេត្តសៀមរាប',
      district_name: 'ក្រុងសៀមរាប',
      max_attendees: 150,
      current_attendees: 45,
      allow_public_registration: true,
      requires_approval: false,
      is_multi_track: false,
      is_published: true,
      tags: ['គ្រូបង្រៀន', 'អភិវឌ្ឍន៍', 'ជំនាញ'],
    },
    {
      event_code: 'EVT-2025-003',
      event_name: 'វេបសិនាពីការវាយតម្លៃសិក្សា',
      event_name_english: 'Online Seminar on Student Assessment',
      event_description: 'រៀនពីវិធីសាស្រ្តវាយតម្លៃសិស្សដោយប្រើប្រាស់ឧបករណ៍ឌីជីថល និង បច្ចេកទេសវាយតម្លៃទំនើប។',
      event_type: 'WEBINAR',
      event_category: 'ASSESSMENT',
      event_format: 'VIRTUAL',
      event_status: 'UPCOMING',
      event_start_date: new Date('2025-02-25'),
      event_end_date: new Date('2025-02-25'),
      registration_deadline: new Date('2025-02-23'),
      virtual_platform: 'Google Meet',
      virtual_meeting_url: 'https://meet.google.com/example',
      max_attendees: 300,
      current_attendees: 189,
      allow_public_registration: true,
      requires_approval: false,
      is_multi_track: false,
      is_published: true,
      tags: ['វេបសិនា', 'វាយតម្លៃ', 'អនឡាញ'],
    },
    {
      event_code: 'EVT-2025-004',
      event_name: 'ពិធីប្រគល់វិញ្ញាបនប័ត្រប្រចាំឆ្នាំ',
      event_name_english: 'Annual Certificate Ceremony',
      event_description: 'ពិធីប្រគល់វិញ្ញាបនប័ត្រដល់គ្រូបង្រៀនដែលបានបញ្ចប់កម្មវិធីបណ្តុះបណ្តាលប្រចាំឆ្នាំ ២០២៤។',
      event_type: 'CEREMONY',
      event_category: 'RECOGNITION',
      event_format: 'IN_PERSON',
      event_status: 'UPCOMING',
      event_start_date: new Date('2025-03-20'),
      event_end_date: new Date('2025-03-20'),
      registration_deadline: new Date('2025-03-15'),
      event_location: 'រាជធានីភ្នំពេញ',
      event_venue: 'ក្រសួងអប់រំ យុវជន និងកីឡា',
      province_name: 'រាជធានីភ្នំពេញ',
      district_name: 'ខណ្ឌដូនពេញ',
      max_attendees: 200,
      current_attendees: 156,
      allow_public_registration: false,
      requires_approval: true,
      is_multi_track: false,
      is_published: true,
      tags: ['វិញ្ញាបនប័ត្រ', 'ពិធី', 'ជោគជ័យ'],
    },
    {
      event_code: 'EVT-2025-005',
      event_name: 'ការប្រជុំបណ្តាញអ្នកអប់រំខេត្តកណ្តាល',
      event_name_english: 'Central Region Educators Networking Meeting',
      event_description: 'ការប្រជុំបណ្តាញសម្រាប់គ្រូបង្រៀន និង អ្នកគ្រប់គ្រងសាលារៀនក្នុងតំបន់ខេត្តកណ្តាល។ ចែករំលែកបទពិសោធន៍ និង ការអនុវត្តល្អបំផុត។',
      event_type: 'NETWORKING',
      event_category: 'COMMUNITY',
      event_format: 'IN_PERSON',
      event_status: 'UPCOMING',
      event_start_date: new Date('2025-03-10'),
      event_end_date: new Date('2025-03-10'),
      registration_deadline: new Date('2025-03-07'),
      event_location: 'ខេត្តកំពង់ចាម',
      event_venue: 'នាយកដ្ឋានអប់រំខេត្ត',
      province_name: 'ខេត្តកំពង់ចាម',
      district_name: 'ក្រុងកំពង់ចាម',
      max_attendees: 100,
      current_attendees: 67,
      allow_public_registration: true,
      requires_approval: false,
      is_multi_track: false,
      is_published: true,
      tags: ['បណ្តាញ', 'ចែករំលែក', 'ខេត្តកណ្តាល'],
    },
    {
      event_code: 'EVT-2025-006',
      event_name: 'សិក្ខាសាលាស្តីពី STEM Education',
      event_name_english: 'STEM Education Workshop',
      event_description: 'រៀនពីវិធីបង្រៀនមុខវិជ្ជាវិទ្យាសាស្ត្រ បច្ចេកវិទ្យា វិស្វកម្ម និង គណិតវិទ្យា តាមរយៈសកម្មភាពអន្តរកម្ម។',
      event_type: 'WORKSHOP',
      event_category: 'STEM',
      event_format: 'HYBRID',
      event_status: 'UPCOMING',
      event_start_date: new Date('2025-04-08'),
      event_end_date: new Date('2025-04-10'),
      registration_deadline: new Date('2025-04-01'),
      event_location: 'ខេត្តបាត់ដំបង',
      event_venue: 'វិទ្យាល័យជំនាញបាត់ដំបង',
      province_name: 'ខេត្តបាត់ដំបង',
      district_name: 'ក្រុងបាត់ដំបង',
      virtual_platform: 'Microsoft Teams',
      virtual_meeting_url: 'https://teams.microsoft.com/example',
      max_attendees: 80,
      current_attendees: 23,
      allow_public_registration: true,
      requires_approval: false,
      is_multi_track: true,
      is_published: true,
      tags: ['STEM', 'វិទ្យាសាស្ត្រ', 'បច្ចេកវិទ្យា'],
    },
  ];

  for (const eventData of events) {
    try {
      const event = await prisma.event.create({
        data: eventData,
      });
      console.log(`✅ Created: ${event.event_name} (${event.event_code})`);
    } catch (error) {
      console.error(`❌ Failed to create ${eventData.event_code}:`, error);
    }
  }

  console.log('\n✅ Sample events creation complete!');
  await prisma.$disconnect();
}

createSampleEvents();
